server {
    listen 80;
    server_name _; # Replace with your domain or Elastic IP

    root /var/www/portfolio;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optimization for static assets
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # Error pages
    error_page 404 /index.html;
}
